# Generated by Django 5.2.6 on 2025-09-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('don_hang_giao_hang', '0001_initial'),
        ('loai_mat_hang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('MaChiTietDonHang', models.AutoField(primary_key=True, serialize=False)),
                ('TenSanPhamDuocGiao', models.CharField(max_length=200, unique=True)),
                ('SoLuong', models.IntegerField(default=0)),
                ('TrongLuong', models.FloatField(default=0)),
                ('TenThuHo', models.CharField(max_length=200)),
                ('MaDonHangGiaoHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='don_hang_giao_hang.donhanggiaohang', unique=True)),
                ('MaLoaiMatHang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loai_mat_hang.loaimathang')),
            ],
        ),
    ]
