# Generated by Django 5.2.6 on 2025-09-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dich_vu', '0001_initial'),
        ('khach_hang', '0001_initial'),
        ('khoang_thoi_gian', '0001_initial'),
        ('khu_vuc', '0001_initial'),
        ('thanh_vien_giao_hang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHangGiaoHang',
            fields=[
                ('MaDonHangGiaoHang', models.AutoField(primary_key=True, serialize=False)),
                ('TenNguoiNhan', models.CharField(max_length=200)),
                ('DiaChiGiaoHang', models.CharField(max_length=200)),
                ('SoDTNguoiNhan', models.CharField(max_length=11)),
                ('NgayGiaoHang', models.DateField()),
                ('PhuongThucThanhToan', models.CharField(max_length=20)),
                ('TrangThaiPheDuyet', models.CharField(max_length=200, null=True)),
                ('TrangThaiGiaoHang', models.CharField(max_length=200, null=True)),
                ('MaDichVu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dich_vu.dichvu')),
                ('MaKhachhang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='khach_hang.khachhang')),
                ('MaKhoangThoiGian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='khoang_thoi_gian.khoangthoigian')),
                ('MaKhuVuc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='khu_vuc.khuvuc')),
                ('MaThanhVienGiaoHang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thanh_vien_giao_hang.thanhviengiaohang')),
            ],
        ),
    ]
