# Generated by Django 5.2.6 on 2025-10-05 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineBiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('biz', models.CharField(max_length=50)),
                ('biz_detail', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineAreaContractedBiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('line_len', models.DecimalField(decimal_places=5, max_digits=14)),
                ('construction_start_date', models.DateTimeField(null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('line_biz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.linebiz')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.section')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=1)),
                ('organization_name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('institution_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='m.institution')),
                ('parent_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='m.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LineAreaAccessAuthorization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('line_area_contracted_biz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.lineareacontractedbiz')),
                ('organization_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAccessAuthorization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accessible_org_code', models.CharField(max_length=50)),
                ('accessible_org_level', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('organization_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPositionRoleMgmt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('organization_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.organization')),
                ('position_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.position')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.role')),
            ],
        ),
        migrations.CreateModel(
            name='RoleScreenMgmt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.role')),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.screen')),
            ],
        ),
        migrations.AddField(
            model_name='linebiz',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.section'),
        ),
        migrations.CreateModel(
            name='UserOrgPositionMgmt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('organization_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.organization')),
                ('position_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m.position')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
