# Generated by Django 5.2.6 on 2025-09-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhuVuc',
            fields=[
                ('MaKhuVuc', models.AutoField(primary_key=True, serialize=False)),
                ('TenKhuVuc', models.CharField(max_length=200)),
            ],
        ),
    ]
