# Generated by Django 5.2.6 on 2025-09-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhVienGiaoHang',
            fields=[
                ('MaThanhVienGiaoHang', models.AutoField(primary_key=True, serialize=False)),
                ('TenThanhVienGiaoHang', models.CharField(max_length=200)),
                ('NgaySinh', models.DateField()),
                ('GioiTinh', models.CharField(max_length=3)),
                ('SoDTThanhVien', models.CharField(max_length=11)),
                ('DiaChiThanhVien', models.CharField(max_length=200)),
            ],
        ),
    ]
