# Generated by Django 5.2.6 on 2025-09-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khoang_thoi_gian', '0001_initial'),
        ('thanh_vien_giao_hang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKyGiaoHang',
            fields=[
                ('MaDangKyGiaoHang', models.AutoField(primary_key=True, serialize=False)),
                ('MaKhoangThoiGian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='khoang_thoi_gian.khoangthoigian')),
                ('MaThanhVienGiaoHang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thanh_vien_giao_hang.thanhviengiaohang')),
            ],
        ),
    ]
