# Generated by Django 5.2.6 on 2025-09-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khu_vuc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKhachHang', models.AutoField(primary_key=True, serialize=False)),
                ('TenKhachHang', models.CharField(max_length=200)),
                ('TenCuaHang', models.CharField(max_length=200)),
                ('SoDTKhachHang', models.CharField(max_length=11)),
                ('DiaChiEmail', models.CharField(max_length=200, null=True)),
                ('DiaChiNhanHang', models.CharField(max_length=200)),
                ('MaKhuVuc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='khu_vuc.khuvuc')),
            ],
        ),
    ]
